"""'Second_migration'
Revision ID: 35c429e44dac
Revises: dcc7164ba6ff
Create Date: 2021-11-27 20:10:46.186647
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c429e44dac'
down_revision = 'dcc7164ba6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_email',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], )
    )
    op.create_table('contact_phone',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_phone')
    op.drop_table('contact_email')
    op.drop_table('phone')
    op.drop_table('email')
    # ### end Alembic commands ###